# Generated by Django 3.2.3 on 2021-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lenses',
            options={'permissions': (('has_access', 'Has access'),)},
        ),
        migrations.AlterField(
            model_name='lenses',
            name='name',
            field=models.CharField(help_text='The most common name of the lens.', max_length=100),
        ),
    ]
