"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


AUTH_USER_MODEL = 'lenses.Users'
GUARDIAN_MONKEY_PATCH = False
DJANGO_NOTIFICATIONS_CONFIG = { 'USE_JSONFIELD': True}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.forms',
    'storages',
    'guardian',
    'sled_registration.apps.RegistrationConfig',  
    'crispy_forms',
    'crispy_bootstrap4',
    'notifications',
    'api',
    'rest_framework',
    'gm2m',
    'widget_tweaks',
    'bootstrap_modal_forms',
    'sled_core',
    'sled_collections',
    'sled_admin_collections',
    'sled_notifications',
    'sled_tasks',
    'sled_queries',
    'sled_instrument',
    'sled_band',
    'sled_papers',
    'sled_data',
    'sled_single_objects',
    'sled_persistent_message',
    'sled_limits',
    'lenses.apps.LensesConfig',
    'sled_groups.apps.GroupsConfig',
    'sled_home.apps.HomeConfig',
    'sled_users.apps.UsersConfig',
    'actstream',
    'multiselectfield',
    'django_select2',
    'nolastlogin',
    'captcha',
    'axes',
]

SITE_ID = 1

ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window

AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesStandaloneBackend', # Should be first
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'axes.middleware.AxesMiddleware', # Should be last
]

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sled_persistent_message.banner_context_processor.current_messages',
            ],
            'libraries': {
                'project_tags': 'templatetags.sled_extras'
            },
        },
    },
]
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'


WSGI_APPLICATION = 'mysite.wsgi.application'


# Content Security Policy
CSP_IMG_SRC = ("'self'",'https://code.jquery.com')
CSP_STYLE_SRC = ("'self'",'https://cdn.jsdelivr.net','https://use.typekit.net','https://p.typekit.net')
CSP_STYLE_SRC_ELEM = ("'self'",'https://cdn.jsdelivr.net','https://fonts.googleapis.com','http://fonts.googleapis.com','https://use.typekit.net','https://p.typekit.net','https://cdn.plot.ly','https://code.jquery.com','https://cdnjs.cloudflare.com')
CSP_STYLE_SRC_ATTR = ("'self'")
CSP_SCRIPT_SRC = ("'self'",'https://cdn.jsdelivr.net','https://code.jquery.com','https://ajax.googleapis.com','https://use.typekit.net')
CSP_SCRIPT_SRC_ELEM = ("'self'",'https://cdn.jsdelivr.net','https://code.jquery.com','https://ajax.googleapis.com','https://use.typekit.net','https://cdn.plot.ly','https://cdnjs.cloudflare.com')
CSP_FONT_SRC = ("'self'",'https://fonts.gstatic.com','http://fonts.gstatic.com','https://use.typekit.net')
CSP_INCLUDE_NONCE_IN = ['style-src-elem','script-src-elem']

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'
USE_I18N = True
USE_L10N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]

# Media files, i.e. user uploaded files
DATA_UPLOAD_MAX_NUMBER_FIELDS = None
FILE_UPLOAD_MAX_MEMORY_SIZE = 1000000
DATA_UPLOAD_MAX_MEMORY_SIZE = None

ACTSTREAM_SETTINGS = {
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'USE_JSONFIELD': True,
    'GFK_FETCH_DEPTH': 1,
}


LOGIN_URL = '/login/'
LOGOUT_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600} 
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    50: 'critical',
}
