site_name: SLED project documentation
site_url: https://example.com/

dev_addr: 127.0.0.1:8001

theme:
    name: readthedocs

nav:
    - Home: index.md
    - SLED classes: sources/api/single_object.md